### ISSUE TITLE
500 Errors when using components

### ISSUE THREAD

**Issue by divisionparzero** [kylefernandadams/box-ui-elements-heroku-template#1]
The weird part is that the uploader and file picker components work on a Community page but not on a Lightning page. None of the other components work anywhere.

Chrome dev console lists a bunch of 500 errors on JS files.

I followed the directions for this application, the Box application and the Salesforce application and everything seems to be correct. I'm thinking maybe a recent Salesforce update might have made things more complicated.

I have attached the dev console messages from the community page with only the working components and still getting errors even though they work. I've also attached the same for the lightning page with the same components and the same folder ID.

In my experience, I would have expected the Lightning page to work and the Community page to not work if anything so this is kind of bizarre.
[lightning page not working.log](https://github.com/kylefernandadams/box-ui-elements-heroku/files/9409804/lightning.page.not.working.log)
[working experience cloud page.log](https://github.com/kylefernandadams/box-ui-elements-heroku/files/9409805/working.experience.cloud.page.log)

**Comment by divisionparzero** [comment]
Box App user needs to be added to all folders/files involved. I really shouldn't be allowed to mess with code late at night.

**Comment by RupertBarrow** [comment]
Thanks @divisionparzero , this is what was missing for me.
